### ISSUE TITLE
[Bug] MentionChannels 4.2.0+ - Broken as of Stable 123305 (2d81cde)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Echological/MentionChannels#10]
MentionChannels 4.2.0+, Commit: 859f07c0086610b794f33e75f8dc989f7ebb5e9f

No longer functioning from stable to canary
```text
Stable 123305 (2d81cde)
BetterDiscord 1.5.2
Host 0.0.266 OS X 10.15.7 (20.6.0)
```
![Screen_Shot_2022-04-09_at_1 05 09_pm](https://user-images.githubusercontent.com/2242880/162554322-934ea93f-44a9-472a-b567-7b85b59a31e2.jpg)

There are no logs in console or debug.log with just the plugin enabled.

**Comment by Echological** [comment]
fixed in newer release, see https://github.com/Echological/MentionChannels/commit/68436a5d13c75aa443c7ea38ce6aa8c66eff274f
