### ISSUE TITLE
Recent Update(Stable 113404 (30b719d)) Broke MentionChannels Again :(

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Echological/MentionChannels#8]
This could be a Lib issue since BDFDB is also having issues, however, I haven't found much evidence that "0PluginLibrary" is also having issues..

another plugin called **BetterInvites** is reporting issues with 0PluginLibrary (Cannot read property '0' of undefined)
however, no logs regarding mention channels were found anywhere...

Full Logs:
[debug.log](https://github.com/Echological/MentionChannels-BD/files/8002023/debug.log)
[discord.com-1643970498769.log](https://github.com/Echological/MentionChannels-BD/files/8002029/discord.com-1643970498769.log)

As you can see from the screenshot the mention channels has gone missing again..
![Screen Shot 2022-02-04 at 9 28 47 pm](https://user-images.githubusercontent.com/2242880/152513683-8b0df1b5-23d9-4c58-bd3d-d885c7bf6044.jpg)

```text
Stable 113404 (30b719d)
BetterDiscord 1.5.0
Host 0.0.264 OS X 10.15.7 (20.6.0)
```

**Comment by Echological** [comment]
BDFDB is a private library, not one that i use

0PluginLibrary is ZeresLib internal

not sure the issue with this, will check when i am home later

**Comment by XxUnkn0wnxX** [comment]
still not working even after recent BD updates..
[Video](https://www.dropbox.com/s/rkfgohjw361b5y8)

**Comment by Echological** [comment]
Yeah its all known by the bd devs, latest update was not intended to fix the specific issue with context menus

**Comment by Echological** [comment]
should be fixed now
